const CONSTANT = {
    TRANSLATE_CLIENT: 'gtx',
    TRANSLATE_COUNT: 0,
    TRANSLATE_TIMEOUT: 60000, 
    WAIT_PER_TRANSLATE_TIMEOUT: 3000,
    TRANSLATE_LIMIT_BEFORE_TIMEOUT: 90,
}

module.exports = {
    CONSTANT
};